### ISSUE TITLE
twig cache

### ISSUE THREAD

**Issue by gpunx** [jheathco/kohana-twig#1]
when installing under kohana 3.0.4.2 i had to add the cache path to the environment key in modules/twig/config/twig.php in order for kohana-twig to use the application/cache/twig directory for cacheing.

**Comment by gpunx** [comment]
in my original post, i had mentioned having to add the cache directory to the extensions key. this was incorrect. sorry about that. it should have been the environment key. i have edited/corrected my original post.

**Comment by jheathco** [comment]
Ok, thanks

**Comment by jheathco** [comment]
So should this issue still be open?

**Comment by gpunx** [comment]
if it has not been fixed in your repository, i would say the repository needs to be updated. btw, nice job on the module!! i am new to kohana and as a django fan, i love twig. it was nice to see that you had created a kohana module for it.
