### ISSUE TITLE
Fatal Error On Guide/API

### ISSUE THREAD

**Issue by daGrevis** [jheathco/kohana-twig#4]
I just enabled module. Then I went to "guide/api to see API, because there are no docs for this module (as far as I know). I got following error: "Fatal error: Declaration of Kohana_Twig_Node_BlockTrans::compile() must be compatible with that of Twig_NodeInterface::compile() in C:\xampp\htdocs\kohana\modules\twig\classes\kohana\twig\node\blocktrans.php on line 4".

I guess it's because I use latest Twig's version. With what version this module is compatible and will there be any new versions for this module? And docs?

**Comment by jheathco** [comment]
@daGrevis Try using this module now.  It should be updated and ready to go for Kohana 3.1.

**Comment by jheathco** [comment]
You'll need to use the Twig fork that I've created as well (it's included with kohana-twig) if you plan on using templates with Kohana's ORM.
